// Danh sách tất cả ngân hàng đang hoạt động tại Việt Nam (cập nhật 2026)
export const VIETNAM_BANKS = [
  { code: "VCB",  name: "Vietcombank",      fullName: "Ngân hàng TMCP Ngoại thương Việt Nam" },
  { code: "VTB",  name: "VietinBank",       fullName: "Ngân hàng TMCP Công Thương Việt Nam" },
  { code: "BIDV", name: "BIDV",             fullName: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam" },
  { code: "AGR",  name: "Agribank",         fullName: "Ngân hàng Nông nghiệp và PTNT Việt Nam" },
  { code: "TCB",  name: "Techcombank",      fullName: "Ngân hàng TMCP Kỹ thương Việt Nam" },
  { code: "MBB",  name: "MB Bank",          fullName: "Ngân hàng TMCP Quân đội" },
  { code: "ACB",  name: "ACB",              fullName: "Ngân hàng TMCP Á Châu" },
  { code: "VPB",  name: "VPBank",           fullName: "Ngân hàng TMCP Việt Nam Thịnh Vượng" },
  { code: "STB",  name: "Sacombank",        fullName: "Ngân hàng TMCP Sài Gòn Thương Tín" },
  { code: "HDB",  name: "HDBank",           fullName: "Ngân hàng TMCP Phát triển TP.HCM" },
  { code: "TPB",  name: "TPBank",           fullName: "Ngân hàng TMCP Tiên Phong" },
  { code: "MSB",  name: "MSB",              fullName: "Ngân hàng TMCP Hàng Hải Việt Nam" },
  { code: "OCB",  name: "OCB",              fullName: "Ngân hàng TMCP Phương Đông" },
  { code: "EIB",  name: "Eximbank",         fullName: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam" },
  { code: "SHB",  name: "SHB",              fullName: "Ngân hàng TMCP Sài Gòn – Hà Nội" },
  { code: "BVB",  name: "BaoVietBank",      fullName: "Ngân hàng TMCP Bảo Việt" },
  { code: "VIB",  name: "VIB",              fullName: "Ngân hàng TMCP Quốc tế Việt Nam" },
  { code: "NVB",  name: "NamABank",         fullName: "Ngân hàng TMCP Nam Á" },
  { code: "BAB",  name: "BacABank",         fullName: "Ngân hàng TMCP Bắc Á" },
  { code: "SCB",  name: "SCB",              fullName: "Ngân hàng TMCP Sài Gòn" },
  { code: "PGB",  name: "PGBank",           fullName: "Ngân hàng TMCP Xăng dầu Petrolimex" },
  { code: "KLB",  name: "KienLongBank",     fullName: "Ngân hàng TMCP Kiên Long" },
  { code: "LPB",  name: "LPBank",           fullName: "Ngân hàng TMCP Lộc Phát Việt Nam" },
  { code: "SEAB", name: "SeABank",          fullName: "Ngân hàng TMCP Đông Nam Á" },
  { code: "ABB",  name: "ABBank",           fullName: "Ngân hàng TMCP An Bình" },
  { code: "VAB",  name: "VietABank",        fullName: "Ngân hàng TMCP Việt Á" },
  { code: "IVB",  name: "IndovinaBank",     fullName: "Ngân hàng TNHH Indovina" },
  { code: "VBSP", name: "VBSP",             fullName: "Ngân hàng Chính sách Xã hội" },
  { code: "VDB",  name: "VDB",              fullName: "Ngân hàng Phát triển Việt Nam" },
  { code: "PBVN", name: "PublicBank",       fullName: "Ngân hàng TNHH MTV Public Việt Nam" },
  { code: "HSBC", name: "HSBC",             fullName: "Ngân hàng TNHH MTV HSBC Việt Nam" },
  { code: "SCB2", name: "Standard Chartered", fullName: "Ngân hàng TNHH MTV Standard Chartered Việt Nam" },
  { code: "CTG2", name: "Citibank",         fullName: "Ngân hàng Citibank Việt Nam" },
  { code: "CAKE", name: "CAKE",             fullName: "Ngân hàng số CAKE by VPBank" },
  { code: "TIMO", name: "Timo",             fullName: "Ngân hàng số Timo by Bản Việt" },
  { code: "MOMO", name: "MoMo",             fullName: "Ví điện tử MoMo" },
  { code: "ZALO", name: "ZaloPay",          fullName: "Ví điện tử ZaloPay" },
  { code: "VNPT", name: "VNPTpay",          fullName: "Ví điện tử VNPT Pay" },
  { code: "VIET", name: "ViettelPay",       fullName: "Ví điện tử Viettel Pay" },
  { code: "SHBF", name: "SHB Finance",      fullName: "Công ty Tài chính TNHH MTV SHB Finance" },
];
